<?php require './templates/task/header.phtml'; ?>

<div class="container mt-5">
    <?php foreach ($list as $item) { ?>
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="<?= $item->imagenProducto; ?>" class="img-fluid rounded-start" alt="Imagen del Producto">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title"><?= $item->nombreProducto; ?></h5>
                        <p class="card-text"><?= $item->idCodigoProducto; ?></p>
                        <p class="card-text"><strong>Precio:</strong>$<?= $item->precio; ?></p>
                        <p class="card-text"><strong>Marca:</strong> <?= $item->marca; ?></p>
                        <p class="card-text"><strong>Categoría:</strong> <?= $item->categoria; ?></p>
                        <a href="list" class="btn btn-primary">Volver</a>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
</div>

<?php require_once 'templates/task/footer.phtml'; ?>
