<?php
require './templates/task/header.phtml';
?>
<div class="mt-1 w-100 mx-auto" style="height: 300px;">
    <table class="table">
        <thead>
            <tr>
                <th class="text-center">Código Producto</th>
                <th class="text-center">Nombre Producto</th>
                <th class="text-center">Precio</th>
                <th class="text-center">Marca</th>
                <th class="text-center">Imagen Producto</th>
                <th class="text-center">Categoria</th>
                <th class="text-center">Acciones</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($list as $item) { ?>
                <tr>
                    <td class="text-center"><?= $item->idCodigoProducto; ?></td>
                    <td class="text-center"><?= $item->nombreProducto; ?></td>
                    <td class="text-center"><?= $item->precio; ?></td>
                    <td class="text-center"><?= $item->marca; ?></td>
                    <td class="text-center"><img src="<?= $item->imagenProducto; ?>" class="imagen" style="max-width: 80px"></td>
                    <td class="text-center"><?= $item->categoria; ?></td>
                    <td class="text-center">
                        <a href="listId/<?= $item->idProducto;?>" class="btn btn-primary">Ver Producto</a>
                        <?php if ($adm) { ?>
                            <a href="removeItem/<?= $item->idProducto; ?>" type="button" class='btn btn-danger ml-auto'>Eliminar</a>
                            <a href="updateItemForm/<?= $item->idProducto; ?>" type="button" class='btn btn-success ml-auto'>Modificar</a>
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<?php
 require_once 'templates/task/footer.phtml';
