
<?php
require './templates/task/header.phtml';   
?>
    <div class="mt-1 w-100 mx-auto" style="height: 300px; ">
        <table class="table">
            <thead>
                <tr>
                    <th class="text-center">Categoria</th>
                    <th class="text-center">Material</th>
                    <th class="text-center">origen</th>
                    <th class="text-center">Motor</th>
                    <th class="text-center">Imagen Categoria</th>
                    <th class="text-center">Acciones</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($categorias as $categoria) { ?>      
                    <tr>
                        <td class="text-center"><?= $categoria->categoria; ?></td>
                        <td class="text-center"><?= $categoria->material; ?></td>
                        <td class="text-center"><?= $categoria->origen; ?></td>
                        <td class="text-center"><?= $categoria->motor; ?></td>
                        <td class="text-center"><img src="<?= $categoria->imagenCategoria; ?>"class="imagen" style="max-width: 80px"></td>
                        <td class="text-center">
                            <a href="categoryId/<?= $categoria->idCategoria;?>" class="btn btn-primary">Ver Productos</a>
                            <?php if (AuthHelper::isAdmin()) { ?>
                            <a href="removeCategory/<?= $categoria->idCategoria; ?>" type="button" class='btn btn-danger ml-auto'>Eliminar</a>
                            <a href="updateCategoryForm/<?= $categoria->idCategoria; ?>" type="button" class='btn btn-success ml-auto'>Modificar</a>
                            <?php } ?>
                        </td>
                        </tr>      
                <?php } ?>
            </tbody>
        </table>
    </div>
        <?php
         require_once 'templates/task/footer.phtml';