<?php
require './templates/header.phtml';
?>
<body>
    <div class="mt-5 w-25 mx-auto" style="height: 300px;">
        <table class="table">
            <thead>
                <tr>
                    <th>Código Producto</th>
                    <th>Nombre Producto</th>
                    <th>Precio</th>
                    <th>Marca</th>
                    <th>Imagen Producto</th>
                    <th>Categoria</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($categorias as $item) { ?>      
                    <tr>
                        <td><?php echo $item->idCodigoProducto; ?></td>
                        <td><?php echo $item->nombreProducto; ?></td>
                        <td><?php echo $item->precio; ?></td>
                        <td><?php echo $item->marca; ?></td>
                        <td><img src="<?php echo $item->imagenProducto; ?>"class="imagen" style="max-width: 60px"></td>
                        <td><?php echo $item->categoria; ?></td>
                        <td><a href="<?php echo $path;?>" class="btn btn-primary">Volver</a></td>   
                    </tr>      
                <?php } ?>
            </tbody>
        </table>
    </div>
        <?php
        require './templates/footer.phtml';