<?php require './templates/task/header.phtml'; ?>
<body>
    <div class="container mt-5">
        <?php foreach($categorias as $item) { ?>
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="<?php echo $item->imagenProducto; ?>" class="img-fluid rounded-start" alt="Imagen del Producto">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title"><?php echo $item->nombreProducto; ?></h5>
                            <p class="card-text"><?php echo $item->idCodigoProducto; ?></p>
                            <p class="card-text"><strong>Precio:</strong>$<?php echo $item->precio; ?></p>
                            <p class="card-text"><strong>Marca:</strong> <?php echo $item->marca; ?></p>
                            <p class="card-text"><strong>Categoría:</strong> <?php echo $item->categoria; ?></p>
                            <a href="<?php echo $path; ?>" class="btn btn-primary">Volver</a>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</body>
<?php require_once 'templates/task/footer.phtml'; ?>