
<?php

require './templates/task/header.phtml';  ?>

    <div class="container mt-3">
        <h2>Carga de Categoria</h2>

        <form action="addCategory" method="POST">
            <div class="mb-1">
                <label for="categoria" class="form-label">Categoría</label>
                <input type="text" class="form-control" id="categoria" name="categoria" required>
            </div>
            <div class="mb-1">
                <label for="material" class="form-label">Material</label>
                <input type="text" class="form-control" id="material" name="material" required>
            </div>
            <div class="mb-1">
                <label for="origen" class="form-label">origen</label>
                <input type="text" class="form-control" id="origen" name="origen" required>
            </div>
            <div class="mb-1">
                <label for="motor" class="form-label">Motor
                    <input type="text" class="form-control" id="motor" name="motor" required>
            </div>
            <div class="mb-1">
                <label for="imagenCategoria" class="form-label">Imagen de la categoria</label>
                <input type="text" class="form-control" id="imagenCategoria" name="imagenCategoria" required>
            </div>
            <button type="submit" class="btn btn-primary">Guardar categoria</button>
        </form>
    </div>

    <?php

    require_once 'templates/task/footer.phtml';
