<?php
    require_once 'templates/task/header.phtml';  ?>
    
    <div class="container mt-5">
        <h2>Modificacion de Producto</h2>
        <form action="updateItem" method="POST">
            <div class="mb-3">                
                <label for="categoria" class="form-label">Categoría</label>
                <select class="form-select" id="categoria" name="idCategoria">
                <?php foreach($categoria as $cat){ ?>    
                <option value="<?php echo $cat->idCategoria;?>"><?php echo $cat->categoria;?></option>
                <?php } ?>   
                </select>
            </div>
            <div class="mb-3">
                <input type="hidden" class="form-control" id="idProducto" name="idProducto" value="<?php echo $id?>">
            </div>
            <div class="mb-3">
                <label for="idCodigoProducto" class="form-label">Código de Producto</label>
                <input type="text" class="form-control" id="idCodigoProducto" name="idCodigoProducto">
            </div>
            <div class="mb-3">
                <label for="nombreProducto" class="form-label">Nombre de Producto</label>
                <input type="text" class="form-control" id="nombreProducto" name="nombreProducto" required>
            </div>
            <div class="mb-3">
                <label for="precio" class="form-label">Precio</label>
                <input type="number" class="form-control" id="precio" name="precio" required>
            </div>
            <div class="mb-3">
                <label for="marca" class="form-label">Marca</label>
                <input type="text" class="form-control" id="marca" name="marca" required>
            </div>
            <div class="mb-3">
                <label for="imagenProducto" class="form-label">URL de la Imagen</label>
                <input type="text" class="form-control" id="imagenProducto" name="imagenProducto">
            </div>
            <button type="submit" class="btn btn-primary">Modificar</button>
        </form>
    </div>

    <?php

    require_once 'templates/task/footer.phtml';

