
<?php
require './templates/header.phtml';   
?>
    <div class="mt-1 w-100 mx-auto" style="height: 300px;">
        <table class="table">
            <thead>
                <tr>
                    <th>Categoria</th>
                    <th>Material</th>
                    <th>origen</th>
                    <th>Motor</th>
                    <th>Imagen Categoria</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($categories as $item) { ?>      
                    <tr>
                        <td><?php echo $item->categoria; ?></td>
                        <td><?php echo $item->material; ?></td>
                        <td><?php echo $item->origen; ?></td>
                        <td><?php echo $item->motor; ?></td>
                        <td><img src="<?php echo $item->imagenProducto; ?>"class="imagen"></td>
                        <td>
                            <a href="categoryId/<?php echo $item->idCategoria; ?>" class="btn btn-primary">Ver Productos</a>
                            <a href="removeCategory/<?php echo $item->idCategoria; ?>" type="button" class='btn btn-danger ml-auto'>Eliminar</a>
                            <a href="updateCategory/<?php echo $item->idCategoria; ?>" type="button" class='btn btn-success ml-auto'>Modificar</a>
                        </td>
                        </tr>      
                <?php } ?>
            </tbody>
        </table>
    </div>
        <?php
        require './templates/footer.phtml';