<?php
require './templates/task/header.phtml';        
        ?>

<ul class="list-group">
        <?php foreach($tasks as $task) { ?>
            <li class="list-group-item item-task <?php if($task->finalizada) echo 'finalizada' ?>">
                <div>
                    <b><?php echo $task->titulo ?></b> | (Prioridad <?php echo $task->prioridad ?>)
                </div>
                <div class="actions">
                    <?php if(!$task->finalizada) { ?> <a href="finalizar/<?php echo $task->id ?>" type="button" class='btn btn-success ml-auto'>Finalizar</a> <?php } ?>
                    <a href="eliminar/<?php echo $task->id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
                </div>
            </li>
        <?php } ?>
        </ul>

        <?php
         require_once 'templates/task/footer.phtml';
    
