<!-- main footer -->

<footer class=" bg-light text-dark pt-5 pb-4">
  <div class="h-50 container text-center text-md-start">
    <div class="h-50 row text-center text-md-start">
      <div class="h-50 col-md3 col-lg-3 col-xl-3 mx-auto mt-3">
          <h5 class="h-50 text-uppercase mb-4 font-weight-bold text-primary"> About</h5>
              <hr class="mb-4">
              <p>
              Consiste en determinar las consecuencias desencadenadas por la falta de los diferentes repuestos, derivado de la observación de factores como el tiempo que toma ordenar un repuesto (en caso de no tenerlo), recibirlo e instalarlo, así como las pérdidas ocasionadas por el tiempo muerto de producción.
              </p>

    </div>

    <div class="col-md3 col-lg-3 col-xl-3 mx-auto mt-3">
          <h5 class="text-uppercase mb-4 font-weight-bold text-primary"> Help you</h5>
              <hr class="mb-4">
              <p>
                    <a href="#" class="text-dark"> manejo de cuenta </a>
              </p>
              <p>
                    <a href="#" class="text-dark"> Tu cuenta </a>
                </p>
                     <a href="#" class="text-dark"> ver mis pedidos </a>
               </p>
               <p>
                     <a href="#" class="text-dark"> ayuda </a>
              </p>

    </div>

    <div class="col-md3 col-lg-3 col-xl-3 mx-auto mt-3">
          <h5 class="text-uppercase mb-4 font-weight-bold text-primary"> Contacto</h5>
              <hr class="mb-4">
              <p>
                  <li class="fas fa-home me-3"> Tandil, Garibaldi 652 </li>
              </p>
              <p>
                  <li class="fas-fa-envelope me-3"> CosmeFulanito@gmail.com </li>
              </p>
              <p>
                  <li class="fas fa-phone me-3"> +54 2494-485623 </li>
              </p>
              <p>
                  <li class="fas fa-print me-3"> +5555555 </li>
              </p>
               
    </div>

    <div class="col-md3 col-lg-3 col-xl-3 mx-auto mt-3">
          <h5 class="text-uppercase mb-4 font-weight-bold text-primary"> 2023 TUDAI UNICEN</h5>
              <hr class="mb-4">
              <span class="text">Integrantes</span>
        <p>
          <li>Cuello Julian</li>
          <li>Vazquez Francisco</li>
         </p>

      </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

     </footer>
 </body>

</html>