
<?php
require './templates/header.phtml';   
?>
<table class="table">
            <thead>
                <tr>
                    <th>Categoria</th>
                    <th>Material</th>
                    <th>origen</th>
                    <th>Motor</th>
                    <th>Imagen Categoría</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($categorias as $item) { ?>      
                    <tr>
                        <td><?php echo $item->categoria; ?></td>
                        <td><?php echo $item->material; ?></td>
                        <td><?php echo $item->origen; ?></td>
                        <td><?php echo $item->motor; ?></td>
                        <td><img src="<?php echo $item->imagenCategoria; ?>"class="imagen"></td>
                        <td><a href="categoryId/<?php echo $item->idCategoria; ?>" class="btn btn-primary">Productos relacionados</a></td>
                    </tr>      
                <?php } ?>
            </tbody>
        </table>
        <?php
        require './templates/footer.phtml';